# Generated by Django 5.1.7 on 2025-03-09 21:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_remove_payinrate_tour_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='date_time',
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
