# Generated by Django 5.1.7 on 2026-03-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_remove_tour_date_time_tour_tour_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='expense_1_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='expense_1_name',
            field=models.CharField(blank=True, help_text='Name of first expense location', max_length=100),
        ),
        migrations.AddField(
            model_name='tour',
            name='expense_2_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='expense_2_name',
            field=models.CharField(blank=True, help_text='Name of second expense location', max_length=100),
        ),
        migrations.AddField(
            model_name='tour',
            name='expense_3_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='expense_3_name',
            field=models.CharField(blank=True, help_text='Name of third expense location', max_length=100),
        ),
        migrations.AddField(
            model_name='tour',
            name='fixed_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed salary paid by Pulse Tours (CZK). Food tours only.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tourtype',
            name='is_food_tour',
            field=models.BooleanField(default=False, help_text='Food tours have a fixed income, no per-pax payin, and tracked expenses.'),
        ),
    ]
